### PR TITLE
fix: add repository of webp-convert dependency

### PR DESCRIPTION
**Pull request by Pascalmh**
as webp-convert is not registered on packagist we have to add it manually

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
In addition to my fork of it?

// Edit: I wrote an email to its maintainer, asking for permission to submit `webp-convert` to Packagist.

**Comment by Pascalmh** [comment]
No, just saw that you forked it afterwards - sorry. The package just can not be found, maybe the the minimum-stability will help, but i am not sure.

**Comment by S1SYPHOS** [comment]
This should be fixed now.
Maybe you could try to install it and give me some feedback:
`composer require s1syphos/kirby-webp:dev-composer` should do the trick. Beware of the `require_once` inside `kirby-webp.php`, the idea being that people using `composer/installers` will always have the vendor folder in der Kirby root.

**Comment by daybugging** [comment]
Works for me ..

**Pull request merged**
